import type { NormalizedHolidayRecord } from "@/lib/ingestion/normalize-malaysia-holidays"

export interface GenerateHolidaysSqlInput {
  year: number
  source: string
  sourceUrl: string
  records: NormalizedHolidayRecord[]
  generatedAt?: Date
}

interface SqlHolidayRecord {
  date: string
  name: string
  normalizedName: string
  isNational: boolean
  affectedStates: string[]
  kind: "holiday" | "observed"
  observedDate: string | null
  replacementForDate: string | null
  replacementReason: string | null
  confidenceScore: number
}

function escapeSqlLiteral(value: string): string {
  return value.replace(/'/g, "''")
}

function toTextArraySql(values: string[]): string {
  if (values.length === 0) {
    return "ARRAY[]::text[]"
  }

  const escaped = values.map((value) => `'${escapeSqlLiteral(value)}'`).join(", ")
  return `ARRAY[${escaped}]::text[]`
}

function toRecord(record: NormalizedHolidayRecord): SqlHolidayRecord {
  const affectedStates = [...record.affectedStates].sort()

  return {
    date: record.date,
    name: record.name,
    normalizedName: record.normalizedName,
    isNational: record.isNational,
    affectedStates,
    kind: record.kind,
    observedDate: record.kind === "observed" ? record.date : null,
    replacementForDate: record.replacementForDate ?? null,
    replacementReason: record.replacementReason ?? null,
    confidenceScore: record.confidenceScore,
  }
}

function dedupeAndSortRecords(records: NormalizedHolidayRecord[]): NormalizedHolidayRecord[] {
  const seen = new Set<string>()
  const unique: NormalizedHolidayRecord[] = []

  for (const record of records) {
    const affectedStatesKey = [...record.affectedStates].sort().join(",")
    const key = `${record.date}|${record.name}|${affectedStatesKey}`
    if (seen.has(key)) {
      continue
    }
    seen.add(key)
    unique.push(record)
  }

  return unique.sort((a, b) => {
    if (a.date === b.date) {
      const byName = a.name.localeCompare(b.name)
      if (byName !== 0) {
        return byName
      }

      const aStates = [...a.affectedStates].sort().join(",")
      const bStates = [...b.affectedStates].sort().join(",")
      return aStates.localeCompare(bStates)
    }
    return a.date.localeCompare(b.date)
  })
}

export function generateHolidaysSql(input: GenerateHolidaysSqlInput): string {
  const generatedAt = input.generatedAt ?? new Date()
  const normalizedRecords = dedupeAndSortRecords(input.records)
  const records = normalizedRecords.map(toRecord)

  const valuesSql = records
    .map((record) => {
      return [
        `('${record.date}'`,
        `'${escapeSqlLiteral(record.name)}'`,
        `${record.isNational}`,
        `${toTextArraySql(record.affectedStates)}`,
        `'${record.kind}'`,
        `${record.observedDate === null ? "null" : `'${record.observedDate}'`}`,
        `${record.replacementForDate === null ? "null" : `'${record.replacementForDate}'`}`,
        `${record.replacementReason === null ? "null" : `'${escapeSqlLiteral(record.replacementReason)}'`}`,
        `'${escapeSqlLiteral(input.source)}'`,
        `'${escapeSqlLiteral(input.sourceUrl)}'`,
        `'${generatedAt.toISOString()}'`,
        `'${escapeSqlLiteral(record.normalizedName)}'`,
        `${record.confidenceScore.toFixed(2)})`,
      ].join(", ")
    })
    .join(",\n  ")

  return `-- Generated by scripts/getyear.ts\n-- Year: ${input.year}\n-- Source: ${input.sourceUrl}\n-- Generated at: ${generatedAt.toISOString()}\n\nbegin;\n\ninsert into public.public_holidays (\n  date,\n  name,\n  is_national,\n  affected_states,\n  kind,\n  observed_date,\n  replacement_for_date,\n  replacement_reason,\n  source,\n  source_url,\n  source_last_seen_at,\n  normalized_name,\n  confidence_score\n)\nvalues\n  ${valuesSql}\non conflict (date, name, affected_states)\ndo update\nset\n  is_national = excluded.is_national,\n  kind = excluded.kind,\n  observed_date = excluded.observed_date,\n  replacement_for_date = excluded.replacement_for_date,\n  replacement_reason = excluded.replacement_reason,\n  source = excluded.source,\n  source_url = excluded.source_url,\n  source_last_seen_at = excluded.source_last_seen_at,\n  normalized_name = excluded.normalized_name,\n  confidence_score = excluded.confidence_score\nwhere public.public_holidays.is_locked = false;\n\ncommit;\n`
}