-- Generated by scripts/getyear.ts
-- Year: 2027
-- Source: https://www.officeholidays.com/countries/malaysia/2027
-- Generated at: 2026-03-13T23:25:28.020Z

begin;

insert into public.public_holidays (
  date,
  name,
  is_national,
  affected_states,
  kind,
  observed_date,
  replacement_for_date,
  replacement_reason,
  source,
  source_url,
  source_last_seen_at,
  normalized_name,
  confidence_score
)
values
  ('2026-12-31', 'New Year''s Day', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'new years day', 0.75),
  ('2027-01-04', 'Isra and Miraj', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'isra and miraj', 0.75),
  ('2027-01-13', 'Birthday of the Sultan of Negeri Sembilan', false, ARRAY['NSN']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'birthday of the sultan of negeri sembilan', 0.85),
  ('2027-01-21', 'Thaipusam', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'thaipusam', 0.75),
  ('2027-01-31', 'Federal Territory Day', false, ARRAY['KUL', 'LBN', 'PJY']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'federal territory day', 0.85),
  ('2027-02-05', 'Chinese New Year', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'chinese new year', 0.75),
  ('2027-02-06', 'Chinese New Year', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'chinese new year', 0.75),
  ('2027-02-06', 'Chinese New Year Holiday', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'chinese new year holiday', 0.75),
  ('2027-02-08', 'Beginning of Ramadan', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'beginning of ramadan', 0.75),
  ('2027-02-19', 'Malaysian Declaration of Independence Day', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'malaysian declaration of independence day', 0.75),
  ('2027-02-24', 'Nuzul Al-Quran Day', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'nuzul alquran day', 0.75),
  ('2027-03-03', 'Anniversary of Installation of the Sultan', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'anniversary of installation of the sultan', 0.75),
  ('2027-03-08', 'Hari Raya Aidilfitri', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'hari raya aidilfitri', 0.75),
  ('2027-03-09', 'Hari Raya Aidilfitri Holiday', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'hari raya aidilfitri holiday', 0.75),
  ('2027-03-10', 'Hari Raya Aidilfitri Holiday', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'hari raya aidilfitri holiday', 0.75),
  ('2027-03-22', 'Birthday of the Sultan of Johor', false, ARRAY['JHR']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'birthday of the sultan of johor', 0.85),
  ('2027-03-25', 'Good Friday', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'good friday', 0.75),
  ('2027-04-14', 'Declaration of Malacca as a Historical City', false, ARRAY['MLK']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'declaration of malacca as a historical city', 0.85),
  ('2027-04-25', 'Birthday of the Sultan of Terengganu', false, ARRAY['TRG']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'birthday of the sultan of terengganu', 0.85),
  ('2027-04-30', 'Labour Day', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'labour day', 0.75),
  ('2027-05-15', 'Hari Raya Haji', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'hari raya haji', 0.75),
  ('2027-05-15', 'Hari Raya Haji Holiday', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'hari raya haji holiday', 0.75),
  ('2027-05-16', 'Birthday of the Raja of Perlis', false, ARRAY['PLS']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'birthday of the raja of perlis', 0.85),
  ('2027-05-19', 'Wesak Day', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'wesak day', 0.75),
  ('2027-05-21', 'The Sultan of Pahang Hol', false, ARRAY['PHG']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'the sultan of pahang hol', 0.85),
  ('2027-05-28', 'Birthday of the Governor of Sabah', false, ARRAY['SBH']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'birthday of the governor of sabah', 0.85),
  ('2027-05-29', 'Pesta Kaamatan', false, ARRAY['SBH']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'pesta kaamatan', 0.85),
  ('2027-05-30', 'Pesta Kaamatan', false, ARRAY['SBH']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'pesta kaamatan', 0.85),
  ('2027-05-31', 'Gawai Dayak', false, ARRAY['SWK']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'gawai dayak', 0.85),
  ('2027-06-01', 'Gawai Dayak', false, ARRAY['SWK']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'gawai dayak', 0.85),
  ('2027-06-05', 'Awal Muharram', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'awal muharram', 0.75),
  ('2027-06-06', 'Birthday of SPB Yang di Pertuan Agong', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'birthday of spb yang di pertuan agong', 0.75),
  ('2027-06-14', 'Birthday of the Sultan of Kedah', false, ARRAY['KDH']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'birthday of the sultan of kedah', 0.85),
  ('2027-07-06', 'George Town Heritage Day', false, ARRAY['PNG']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'george town heritage day', 0.85),
  ('2027-07-09', 'Birthday of the Governor', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'birthday of the governor', 0.75),
  ('2027-07-21', 'Sarawak Day', false, ARRAY['SWK']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'sarawak day', 0.85),
  ('2027-07-29', 'Birthday of the Sultan of Pahang', false, ARRAY['PHG']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'birthday of the sultan of pahang', 0.85),
  ('2027-07-30', 'The Sultan of Johor Hol', false, ARRAY['JHR']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'the sultan of johor hol', 0.85),
  ('2027-08-14', 'Maulidur Rasul', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'maulidur rasul', 0.75),
  ('2027-08-23', 'Melaka Governor''s Birthday', false, ARRAY['MLK']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'melaka governors birthday', 0.85),
  ('2027-08-30', 'National Day', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'national day', 0.75),
  ('2027-09-15', 'Malaysia Day', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'malaysia day', 0.75),
  ('2027-09-28', 'Birthday of the Sultan of Kelantan', false, ARRAY['KTN']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'birthday of the sultan of kelantan', 0.85),
  ('2027-09-29', 'Birthday of the Sultan of Kelantan Holiday', false, ARRAY['KTN']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'birthday of the sultan of kelantan holiday', 0.85),
  ('2027-10-08', 'Birthday of the Governor of Sarawak', false, ARRAY['SWK']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'birthday of the governor of sarawak', 0.85),
  ('2027-10-28', 'Deepavali', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'deepavali', 0.75),
  ('2027-11-04', 'Birthday of the Sultan of Perak', false, ARRAY['PRK']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'birthday of the sultan of perak', 0.85),
  ('2027-12-10', 'Birthday of The Sultan of Selangor', false, ARRAY['SGR']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'birthday of the sultan of selangor', 0.85),
  ('2027-12-24', 'Christmas Day', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'christmas day', 0.75),
  ('2027-12-24', 'Isra and Miraj', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2027', '2026-03-13T23:25:28.020Z', 'isra and miraj', 0.75)
on conflict (date, name, affected_states)
do update
set
  is_national = excluded.is_national,
  kind = excluded.kind,
  observed_date = excluded.observed_date,
  replacement_for_date = excluded.replacement_for_date,
  replacement_reason = excluded.replacement_reason,
  source = excluded.source,
  source_url = excluded.source_url,
  source_last_seen_at = excluded.source_last_seen_at,
  normalized_name = excluded.normalized_name,
  confidence_score = excluded.confidence_score
where public.public_holidays.is_locked = false;

commit;
