-- Generated by scripts/getyear.ts
-- Year: 2026
-- Source: https://www.officeholidays.com/countries/malaysia/2026
-- Generated at: 2026-03-13T16:29:45.171Z

begin;

insert into public.public_holidays (
  date,
  name,
  is_national,
  affected_states,
  kind,
  observed_date,
  replacement_for_date,
  replacement_reason,
  source,
  source_url,
  source_last_seen_at,
  normalized_name,
  confidence_score
)
values
  ('2025-12-31', 'New Year''s Day', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'new years day', 0.75),
  ('2026-01-13', 'Birthday of the Sultan of Negeri Sembilan', false, ARRAY['NSN']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'birthday of the sultan of negeri sembilan', 0.85),
  ('2026-01-16', 'Isra and Miraj', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'isra and miraj', 0.75),
  ('2026-01-17', 'Isra and Miraj (in lieu)', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'isra and miraj ', 0.75),
  ('2026-01-31', 'Thaipusam', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'thaipusam', 0.75),
  ('2026-02-01', 'Federal Territory Day', false, ARRAY['KUL', 'LBN', 'PJY']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'federal territory day', 0.85),
  ('2026-02-01', 'Thaipusam (in lieu)', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'thaipusam ', 0.75),
  ('2026-02-02', 'Thaipusam (in lieu)', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'thaipusam ', 0.75),
  ('2026-02-16', 'Chinese New Year', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'chinese new year', 0.75),
  ('2026-02-17', 'Chinese New Year Holiday', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'chinese new year holiday', 0.75),
  ('2026-02-18', 'Beginning of Ramadan', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'beginning of ramadan', 0.75),
  ('2026-02-19', 'Malaysian Declaration of Independence Day', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'malaysian declaration of independence day', 0.75),
  ('2026-03-03', 'Anniversary of Installation of the Sultan', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'anniversary of installation of the sultan', 0.75),
  ('2026-03-06', 'Nuzul Al-Quran Day', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'nuzul alquran day', 0.75),
  ('2026-03-07', 'Nuzul Al-Quran Day (in lieu)', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'nuzul alquran day ', 0.75),
  ('2026-03-20', 'Hari Raya Aidilfitri', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'hari raya aidilfitri', 0.75),
  ('2026-03-21', 'Hari Raya Aidilfitri Holiday', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'hari raya aidilfitri holiday', 0.75),
  ('2026-03-22', 'Birthday of the Sultan of Johor', false, ARRAY['JHR']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'birthday of the sultan of johor', 0.85),
  ('2026-03-22', 'Hari Raya Aidilfitri Holiday', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'hari raya aidilfitri holiday', 0.75),
  ('2026-03-23', 'Hari Raya Aidilfitri Holiday', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'hari raya aidilfitri holiday', 0.75),
  ('2026-04-02', 'Good Friday', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'good friday', 0.75),
  ('2026-04-14', 'Declaration of Malacca as a Historical City', false, ARRAY['MLK']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'declaration of malacca as a historical city', 0.85),
  ('2026-04-25', 'Birthday of the Sultan of Terengganu', false, ARRAY['TRG']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'birthday of the sultan of terengganu', 0.85),
  ('2026-04-30', 'Labour Day', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'labour day', 0.75),
  ('2026-05-16', 'Birthday of the Raja of Perlis', false, ARRAY['PLS']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'birthday of the raja of perlis', 0.85),
  ('2026-05-17', 'Birthday of the Raja of Perlis (in lieu)', false, ARRAY['PLS']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'birthday of the raja of perlis ', 0.85),
  ('2026-05-21', 'The Sultan of Pahang Hol', false, ARRAY['PHG']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'the sultan of pahang hol', 0.85),
  ('2026-05-25', 'Arafat (Haj) Day', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'arafat day', 0.75),
  ('2026-05-26', 'Hari Raya Haji', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'hari raya haji', 0.75),
  ('2026-05-27', 'Hari Raya Haji Holiday', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'hari raya haji holiday', 0.75),
  ('2026-05-29', 'Birthday of the Governor of Sabah', false, ARRAY['SBH']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'birthday of the governor of sabah', 0.85),
  ('2026-05-29', 'Pesta Kaamatan', false, ARRAY['SBH']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'pesta kaamatan', 0.85),
  ('2026-05-30', 'Pesta Kaamatan', false, ARRAY['SBH']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'pesta kaamatan', 0.85),
  ('2026-05-30', 'Wesak Day', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'wesak day', 0.75),
  ('2026-05-31', 'Birthday of SPB Yang di Pertuan Agong', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'birthday of spb yang di pertuan agong', 0.75),
  ('2026-05-31', 'Gawai Dayak', false, ARRAY['SWK']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'gawai dayak', 0.85),
  ('2026-06-01', 'Gawai Dayak', false, ARRAY['SWK']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'gawai dayak', 0.85),
  ('2026-06-02', 'Wesak Day (in lieu)', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'wesak day ', 0.75),
  ('2026-06-03', 'Gawai Dayak (in lieu)', false, ARRAY['SWK']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'gawai dayak ', 0.85),
  ('2026-06-16', 'Awal Muharram', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'awal muharram', 0.75),
  ('2026-06-20', 'Birthday of the Sultan of Kedah', false, ARRAY['KDH']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'birthday of the sultan of kedah', 0.85),
  ('2026-07-06', 'George Town Heritage Day', false, ARRAY['PNG']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'george town heritage day', 0.85),
  ('2026-07-10', 'Birthday of the Governor', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'birthday of the governor', 0.75),
  ('2026-07-20', 'The Sultan of Johor Hol', false, ARRAY['JHR']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'the sultan of johor hol', 0.85),
  ('2026-07-21', 'Sarawak Day', false, ARRAY['SWK']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'sarawak day', 0.85),
  ('2026-07-30', 'Birthday of the Sultan of Pahang', false, ARRAY['PHG']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'birthday of the sultan of pahang', 0.85),
  ('2026-08-23', 'Melaka Governor''s Birthday', false, ARRAY['MLK']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'melaka governors birthday', 0.85),
  ('2026-08-24', 'Maulidur Rasul', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'maulidur rasul', 0.75),
  ('2026-08-30', 'National Day', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'national day', 0.75),
  ('2026-09-15', 'Malaysia Day', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'malaysia day', 0.75),
  ('2026-09-28', 'Birthday of the Sultan of Kelantan', false, ARRAY['KTN']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'birthday of the sultan of kelantan', 0.85),
  ('2026-09-29', 'Birthday of the Sultan of Kelantan Holiday', false, ARRAY['KTN']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'birthday of the sultan of kelantan holiday', 0.85),
  ('2026-10-09', 'Birthday of the Governor of Sarawak', false, ARRAY['SWK']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'birthday of the governor of sarawak', 0.85),
  ('2026-11-05', 'Birthday of the Sultan of Perak', false, ARRAY['PRK']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'birthday of the sultan of perak', 0.85),
  ('2026-11-07', 'Deepavali', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'deepavali', 0.75),
  ('2026-11-08', 'Deepavali (in lieu)', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'deepavali ', 0.75),
  ('2026-12-10', 'Birthday of The Sultan of Selangor', false, ARRAY['SGR']::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'birthday of the sultan of selangor', 0.85),
  ('2026-12-24', 'Christmas Day', true, ARRAY[]::text[], 'holiday', null, null, null, 'officeholidays', 'https://www.officeholidays.com/countries/malaysia/2026', '2026-03-13T16:29:45.171Z', 'christmas day', 0.75)
on conflict (date, name, affected_states)
do update
set
  is_national = excluded.is_national,
  kind = excluded.kind,
  observed_date = excluded.observed_date,
  replacement_for_date = excluded.replacement_for_date,
  replacement_reason = excluded.replacement_reason,
  source = excluded.source,
  source_url = excluded.source_url,
  source_last_seen_at = excluded.source_last_seen_at,
  normalized_name = excluded.normalized_name,
  confidence_score = excluded.confidence_score
where public.public_holidays.is_locked = false;

commit;
