create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  preferred_state text,
  preferred_leave_budget int,
  preferred_language text,
  preferred_tone text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.saved_plans (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  state text not null,
  year int not null,
  annual_leave_budget int not null,
  opportunity_payload jsonb not null,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.generated_drafts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  language text not null,
  tone text not null,
  leave_dates text[] not null,
  reason text not null,
  draft_content text not null,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.saved_plans enable row level security;
alter table public.generated_drafts enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
  on public.profiles for select using (auth.uid() = id);

drop policy if exists "profiles_upsert_own" on public.profiles;
create policy "profiles_upsert_own"
  on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "saved_plans_select_own" on public.saved_plans;
create policy "saved_plans_select_own"
  on public.saved_plans for select using (auth.uid() = user_id);

drop policy if exists "saved_plans_write_own" on public.saved_plans;
create policy "saved_plans_write_own"
  on public.saved_plans for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "generated_drafts_select_own" on public.generated_drafts;
create policy "generated_drafts_select_own"
  on public.generated_drafts for select using (auth.uid() = user_id);

drop policy if exists "generated_drafts_write_own" on public.generated_drafts;
create policy "generated_drafts_write_own"
  on public.generated_drafts for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create index if not exists saved_plans_user_idx on public.saved_plans(user_id, created_at desc);
create index if not exists generated_drafts_user_idx on public.generated_drafts(user_id, created_at desc);
