create table if not exists public.public_holidays (
  id bigint generated by default as identity primary key,
  date date not null,
  name text not null,
  is_national boolean not null default false,
  affected_states text[] not null default '{}',
  kind text not null default 'holiday' check (kind in ('holiday', 'observed')),
  year int generated always as (extract(year from date)) stored,
  observed_date date,
  replacement_for_date date,
  replacement_reason text,
  source text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint public_holidays_unique_event unique (date, name, affected_states),
  constraint replacement_meta_guard check (
    (kind = 'observed' and replacement_for_date is not null)
    or (kind = 'holiday' and replacement_for_date is null)
  )
);

create index if not exists public_holidays_date_idx on public.public_holidays (date);
create index if not exists public_holidays_observed_date_idx on public.public_holidays (observed_date);
create index if not exists public_holidays_year_idx on public.public_holidays (year);
create index if not exists public_holidays_affected_states_gin_idx on public.public_holidays using gin (affected_states);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_public_holidays_updated_at on public.public_holidays;
create trigger trg_public_holidays_updated_at
before update on public.public_holidays
for each row
execute procedure public.set_updated_at();

insert into public.public_holidays (date, name, is_national, affected_states, kind, observed_date, replacement_for_date, replacement_reason, source)
values
  ('2026-02-01', 'Thaipusam', false, '{KDH,PRK,PNG,SGR,KUL,LBN,PJY}', 'holiday', null, null, null, 'seed_v1'),
  ('2026-02-01', 'Hari Wilayah Persekutuan', false, '{KUL,LBN,PJY}', 'holiday', null, null, null, 'seed_v1'),
  ('2026-02-02', 'Cuti Ganti Thaipusam', false, '{KDH,PRK,PNG,SGR,KUL,LBN,PJY}', 'observed', '2026-02-02', '2026-02-01', 'Sunday replacement', 'seed_v1'),
  ('2026-02-03', 'Cuti Ganti Hari Wilayah Persekutuan', false, '{KUL,LBN,PJY}', 'observed', '2026-02-03', '2026-02-01', 'Second overlap replacement day', 'seed_v1'),
  ('2026-02-17', 'Tahun Baru Cina', true, '{}', 'holiday', null, null, null, 'seed_v1'),
  ('2026-02-18', 'Tahun Baru Cina (Hari Kedua)', true, '{}', 'holiday', null, null, null, 'seed_v1'),
  ('2026-03-21', 'Hari Raya Aidilfitri', true, '{}', 'holiday', null, null, null, 'seed_v1'),
  ('2026-03-22', 'Hari Raya Aidilfitri (Hari Kedua)', true, '{}', 'holiday', null, null, null, 'seed_v1'),
  ('2026-03-23', 'Cuti Ganti Hari Raya Aidilfitri', true, '{}', 'observed', '2026-03-23', '2026-03-22', 'Sunday replacement', 'seed_v1'),
  ('2026-03-24', 'Cuti Ganti Hari Raya Aidilfitri (Tambahan)', true, '{}', 'observed', '2026-03-24', '2026-03-21', 'Weekend overlap handling', 'seed_v1'),
  ('2026-05-27', 'Hari Raya Haji', true, '{}', 'holiday', null, null, null, 'seed_v1'),
  ('2026-09-16', 'Hari Malaysia', true, '{}', 'holiday', null, null, null, 'seed_v1')
on conflict do nothing;
