create table if not exists public.holiday_ingestion_runs (
  id bigint generated by default as identity primary key,
  year int not null,
  source text not null,
  source_url text,
  status text not null check (status in ('running', 'success', 'failed', 'dry_run')),
  inserted_count int not null default 0,
  updated_count int not null default 0,
  skipped_count int not null default 0,
  anomaly_count int not null default 0,
  checksum text,
  warning_messages text[] not null default '{}',
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.holiday_staging (
  id bigint generated by default as identity primary key,
  ingestion_run_id bigint not null references public.holiday_ingestion_runs(id) on delete cascade,
  year int not null,
  source text not null,
  source_url text,
  date date not null,
  weekday text,
  name text not null,
  raw_row jsonb not null,
  normalized_name text,
  inferred_states text[] not null default '{}',
  inferred_is_national boolean,
  confidence_score numeric(5,4),
  anomaly_reason text,
  created_at timestamptz not null default now()
);

alter table public.public_holidays
  add column if not exists source_url text,
  add column if not exists source_last_seen_at timestamptz,
  add column if not exists ingestion_run_id bigint references public.holiday_ingestion_runs(id),
  add column if not exists is_locked boolean not null default false,
  add column if not exists normalized_name text,
  add column if not exists confidence_score numeric(5,4);

create index if not exists holiday_ingestion_runs_year_idx on public.holiday_ingestion_runs(year);
create index if not exists holiday_ingestion_runs_status_idx on public.holiday_ingestion_runs(status);
create index if not exists holiday_staging_run_idx on public.holiday_staging(ingestion_run_id);
create index if not exists holiday_staging_year_idx on public.holiday_staging(year);
create index if not exists public_holidays_locked_idx on public.public_holidays(is_locked);
create index if not exists public_holidays_source_idx on public.public_holidays(source);
create index if not exists public_holidays_normalized_name_idx on public.public_holidays(normalized_name);
