import type { PublicHoliday } from "@/lib/domain/holidays"

export const HOLIDAY_FALLBACK_YEAR = 2027

export const HOLIDAY_FALLBACK_HOLIDAYS: PublicHoliday[] = [
  {
    date: "2026-12-31",
    name: "New Year's Day",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-01-04",
    name: "Isra and Miraj",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-01-13",
    name: "Birthday of the Sultan of Negeri Sembilan",
    isNational: false,
    affectedStates: ["NSN"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-01-21",
    name: "Thaipusam",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-01-31",
    name: "Federal Territory Day",
    isNational: false,
    affectedStates: ["KUL", "LBN", "PJY"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-02-05",
    name: "Chinese New Year",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-02-06",
    name: "Chinese New Year",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-02-06",
    name: "Chinese New Year Holiday",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-02-08",
    name: "Beginning of Ramadan",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-02-19",
    name: "Malaysian Declaration of Independence Day",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-02-24",
    name: "Nuzul Al-Quran Day",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-03-03",
    name: "Anniversary of Installation of the Sultan",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-03-08",
    name: "Hari Raya Aidilfitri",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-03-09",
    name: "Hari Raya Aidilfitri Holiday",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-03-10",
    name: "Hari Raya Aidilfitri Holiday",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-03-22",
    name: "Birthday of the Sultan of Johor",
    isNational: false,
    affectedStates: ["JHR"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-03-25",
    name: "Good Friday",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-04-14",
    name: "Declaration of Malacca as a Historical City",
    isNational: false,
    affectedStates: ["MLK"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-04-25",
    name: "Birthday of the Sultan of Terengganu",
    isNational: false,
    affectedStates: ["TRG"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-04-30",
    name: "Labour Day",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-05-15",
    name: "Hari Raya Haji",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-05-15",
    name: "Hari Raya Haji Holiday",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-05-16",
    name: "Birthday of the Raja of Perlis",
    isNational: false,
    affectedStates: ["PLS"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-05-19",
    name: "Wesak Day",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-05-21",
    name: "The Sultan of Pahang Hol",
    isNational: false,
    affectedStates: ["PHG"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-05-28",
    name: "Birthday of the Governor of Sabah",
    isNational: false,
    affectedStates: ["SBH"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-05-29",
    name: "Pesta Kaamatan",
    isNational: false,
    affectedStates: ["SBH"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-05-30",
    name: "Pesta Kaamatan",
    isNational: false,
    affectedStates: ["SBH"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-05-31",
    name: "Gawai Dayak",
    isNational: false,
    affectedStates: ["SWK"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-06-01",
    name: "Gawai Dayak",
    isNational: false,
    affectedStates: ["SWK"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-06-05",
    name: "Awal Muharram",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-06-06",
    name: "Birthday of SPB Yang di Pertuan Agong",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-06-14",
    name: "Birthday of the Sultan of Kedah",
    isNational: false,
    affectedStates: ["KDH"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-07-06",
    name: "George Town Heritage Day",
    isNational: false,
    affectedStates: ["PNG"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-07-09",
    name: "Birthday of the Governor",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-07-21",
    name: "Sarawak Day",
    isNational: false,
    affectedStates: ["SWK"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-07-29",
    name: "Birthday of the Sultan of Pahang",
    isNational: false,
    affectedStates: ["PHG"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-07-30",
    name: "The Sultan of Johor Hol",
    isNational: false,
    affectedStates: ["JHR"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-08-14",
    name: "Maulidur Rasul",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-08-23",
    name: "Melaka Governor's Birthday",
    isNational: false,
    affectedStates: ["MLK"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-08-30",
    name: "National Day",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-09-15",
    name: "Malaysia Day",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-09-28",
    name: "Birthday of the Sultan of Kelantan",
    isNational: false,
    affectedStates: ["KTN"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-09-29",
    name: "Birthday of the Sultan of Kelantan Holiday",
    isNational: false,
    affectedStates: ["KTN"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-10-08",
    name: "Birthday of the Governor of Sarawak",
    isNational: false,
    affectedStates: ["SWK"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-10-28",
    name: "Deepavali",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-11-04",
    name: "Birthday of the Sultan of Perak",
    isNational: false,
    affectedStates: ["PRK"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-12-10",
    name: "Birthday of The Sultan of Selangor",
    isNational: false,
    affectedStates: ["SGR"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-12-24",
    name: "Christmas Day",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2027-12-24",
    name: "Isra and Miraj",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
]
