import type { PublicHoliday } from "@/lib/domain/holidays"

export const HOLIDAY_FALLBACK_YEAR = 2026

export const HOLIDAY_FALLBACK_HOLIDAYS: PublicHoliday[] = [
  {
    date: "2025-12-31",
    name: "New Year's Day",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-01-13",
    name: "Birthday of the Sultan of Negeri Sembilan",
    isNational: false,
    affectedStates: ["NSN"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-01-16",
    name: "Isra and Miraj",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-01-17",
    name: "Isra and Miraj (in lieu)",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-01-31",
    name: "Thaipusam",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-02-01",
    name: "Federal Territory Day",
    isNational: false,
    affectedStates: ["KUL", "LBN", "PJY"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-02-01",
    name: "Thaipusam (in lieu)",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-02-02",
    name: "Thaipusam (in lieu)",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-02-16",
    name: "Chinese New Year",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-02-17",
    name: "Chinese New Year Holiday",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-02-18",
    name: "Beginning of Ramadan",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-02-19",
    name: "Malaysian Declaration of Independence Day",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-03-03",
    name: "Anniversary of Installation of the Sultan",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-03-06",
    name: "Nuzul Al-Quran Day",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-03-07",
    name: "Nuzul Al-Quran Day (in lieu)",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-03-20",
    name: "Hari Raya Aidilfitri",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-03-21",
    name: "Hari Raya Aidilfitri Holiday",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-03-22",
    name: "Birthday of the Sultan of Johor",
    isNational: false,
    affectedStates: ["JHR"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-03-22",
    name: "Hari Raya Aidilfitri Holiday",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-03-23",
    name: "Hari Raya Aidilfitri Holiday",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-04-02",
    name: "Good Friday",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-04-14",
    name: "Declaration of Malacca as a Historical City",
    isNational: false,
    affectedStates: ["MLK"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-04-25",
    name: "Birthday of the Sultan of Terengganu",
    isNational: false,
    affectedStates: ["TRG"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-04-30",
    name: "Labour Day",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-05-16",
    name: "Birthday of the Raja of Perlis",
    isNational: false,
    affectedStates: ["PLS"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-05-17",
    name: "Birthday of the Raja of Perlis (in lieu)",
    isNational: false,
    affectedStates: ["PLS"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-05-21",
    name: "The Sultan of Pahang Hol",
    isNational: false,
    affectedStates: ["PHG"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-05-25",
    name: "Arafat (Haj) Day",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-05-26",
    name: "Hari Raya Haji",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-05-27",
    name: "Hari Raya Haji Holiday",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-05-29",
    name: "Birthday of the Governor of Sabah",
    isNational: false,
    affectedStates: ["SBH"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-05-29",
    name: "Pesta Kaamatan",
    isNational: false,
    affectedStates: ["SBH"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-05-30",
    name: "Pesta Kaamatan",
    isNational: false,
    affectedStates: ["SBH"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-05-30",
    name: "Wesak Day",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-05-31",
    name: "Birthday of SPB Yang di Pertuan Agong",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-05-31",
    name: "Gawai Dayak",
    isNational: false,
    affectedStates: ["SWK"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-06-01",
    name: "Gawai Dayak",
    isNational: false,
    affectedStates: ["SWK"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-06-02",
    name: "Wesak Day (in lieu)",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-06-03",
    name: "Gawai Dayak (in lieu)",
    isNational: false,
    affectedStates: ["SWK"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-06-16",
    name: "Awal Muharram",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-06-20",
    name: "Birthday of the Sultan of Kedah",
    isNational: false,
    affectedStates: ["KDH"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-07-06",
    name: "George Town Heritage Day",
    isNational: false,
    affectedStates: ["PNG"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-07-10",
    name: "Birthday of the Governor",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-07-20",
    name: "The Sultan of Johor Hol",
    isNational: false,
    affectedStates: ["JHR"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-07-21",
    name: "Sarawak Day",
    isNational: false,
    affectedStates: ["SWK"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-07-30",
    name: "Birthday of the Sultan of Pahang",
    isNational: false,
    affectedStates: ["PHG"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-08-23",
    name: "Melaka Governor's Birthday",
    isNational: false,
    affectedStates: ["MLK"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-08-24",
    name: "Maulidur Rasul",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-08-30",
    name: "National Day",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-09-15",
    name: "Malaysia Day",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-09-28",
    name: "Birthday of the Sultan of Kelantan",
    isNational: false,
    affectedStates: ["KTN"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-09-29",
    name: "Birthday of the Sultan of Kelantan Holiday",
    isNational: false,
    affectedStates: ["KTN"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-10-09",
    name: "Birthday of the Governor of Sarawak",
    isNational: false,
    affectedStates: ["SWK"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-11-05",
    name: "Birthday of the Sultan of Perak",
    isNational: false,
    affectedStates: ["PRK"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-11-07",
    name: "Deepavali",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-11-08",
    name: "Deepavali (in lieu)",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-12-10",
    name: "Birthday of The Sultan of Selangor",
    isNational: false,
    affectedStates: ["SGR"],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
  {
    date: "2026-12-24",
    name: "Christmas Day",
    isNational: true,
    affectedStates: [],
    kind: "holiday",
    replacementForDate: undefined,
    replacementReason: undefined,
  },
]
